import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Stalemate, Poly } from "next/font/google"; // Import font Poly
import "./globals.css";
import Navbar from "../components/navbar/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Konfigurasi font Stalemate
const stalemate = Stalemate({
  weight: "400",
  variable: "--font-stalemate",
  subsets: ["latin"],
  display: "swap",
});

// Konfigurasi font Poly
const poly = Poly({
  weight: ["400", "400"], // Poly memiliki weight '400' untuk regular dan italic
  style: ["normal", "italic"], // Tentukan style yang tersedia
  variable: "--font-poly",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${stalemate.variable} ${poly.variable} antialiased`}
        style={{ fontFamily: "var(--font-poly)" }} // Atur font default menjadi Poly
      >
        <Navbar /> 
        {children}
      </body>
    </html>
  );
}